module.exports = [{
    "isActive": false,
    "title": "布局设置",
    "isShow": false,
    "ectGridList": [{
        "class": "ect-grid-1",
        "isShow": true,
    }, {
        "class": "ect-grid-2",
        "isShow": true,
    }, {
        "class": "ect-grid-3",
        "isShow": true,
    }, {
        "class": "ect-grid-4",
        "isShow": true,
    }, {
        "class": "ect-grid-5",
        "isShow": true,
    }, {
        "class": "ect-grid-auto",
        "isShow": true,
    }]
}, {
    "isActive": false,
    "title": "基础组件",
    "isShow": true,
    "ectConList": [{
        "icon": "icon-title",
        "text": "标题",
        "module": "title",
        "isShow": true,
    }, {
        "icon": "icon-link",
        "text": "文本链接",
        "module": "link",
        "isShow": false,
    }, {
        "icon": "icon-rich-text",
        "text": "富文本",
        "module": "editor",
        "isShow": false,
    }, {
        "icon": "icon-image",
        "text": "图片",
        "module": "image",
        "isShow": false,
    }, {
        "icon": "icon-button",
        "text": "按钮",
        "module": "button",
        "isShow": false,
    }, {
        "icon": "icon-line",
        "text": "辅助线",
        "module": "line",
        "isShow": true,
    }, {
        "icon": "icon-blank",
        "text": "辅助空白",
        "module": "blank",
        "isShow": true,
    }]
}, {
    "isActive": false,
    "title": "工具组件",
    "isShow": true,
    "ectConList": [{
        "icon": "icon-map",
        "text": "图片导航",
        "module": "nav",
        "isShow": true,
    }, {
        "icon": "icon-search",
        "text": "搜索",
        "module": "search",
        "isShow": true,
    }, {
        "icon": "icon-announcement",
        "text": "公告",
        "module": "announcement",
        "isShow": true,
    }]
}, {
    "isActive": false,
    "title": "高级组件",
    "isShow": true,
    "ectConList": [{
        "icon": "icon-pictures",
        "text": "图片广告",
        "module": "picture",
        "isShow": true,
    }, {
        "icon": "icon-product-list",
        "text": "商品列表",
        "module": "product",
        "isShow": true,
    }, {
        "icon": "icon-grouping",
        "text": "商品分组",
        "module": "group",
        "isShow": false,
    }, {
        "icon": "icon-text-list",
        "text": "文字列表",
        "module": "list",
        "isShow": true,
    }, {
        "icon": "icon-coupon",
        "text": "优惠券",
        "module": "coupon",
        "isShow": false,
    }]
}, {
    "isActive": false,
    "title": "活动组件",
    "isShow": true,
    "ectConList": [{
        "icon": "icon-spike",
        "text": "秒杀",
        "module": "spike",
        "isShow": true,
    }, {
        "icon": "icon-sale",
        "text": "限时折扣",
        "module": "sale",
        "isShow": false,
    }]
}];
